import { z } from 'zod';

export interface ConfigKeyMetadata {
    key: string;
    label: string;
    description: string;
    category: 'polling' | 'review' | 'claude' | 'storage' | 'server' | 'providers';
    type: 'number' | 'boolean' | 'string' | 'enum';
    enumValues?: string[];
    default: unknown;
    editable: boolean;
    requiresRestart: boolean;
    validation: z.ZodType<unknown>;
    sensitive: boolean;
}

export const CONFIG_REGISTRY: ConfigKeyMetadata[] = [
    {
        key: 'polling.intervalSeconds',
        label: 'Polling Interval',
        description: 'How often to check for new PRs and commits, in seconds. Lower values mean faster detection but more API calls.',
        category: 'polling',
        type: 'number',
        default: 3600,
        editable: true,
        requiresRestart: false,
        validation: z.number().min(30).max(86400),
        sensitive: false,
    },
    {
        key: 'review.retentionDays',
        label: 'Review Retention Period',
        description: 'Reviews older than this many days are automatically deleted. Set to 0 to keep reviews indefinitely.',
        category: 'review',
        type: 'number',
        default: 90,
        editable: true,
        requiresRestart: false,
        validation: z.number().min(0).max(3650),
        sensitive: false,
    },
    {
        key: 'review.skipDrafts',
        label: 'Skip Draft PRs',
        description: 'When enabled, draft pull requests are ignored during polling.',
        category: 'review',
        type: 'boolean',
        default: true,
        editable: true,
        requiresRestart: false,
        validation: z.boolean(),
        sensitive: false,
    },
    {
        key: 'review.maxFilesChanged',
        label: 'Max Files Changed',
        description: 'PRs with more changed files than this are skipped. Prevents extremely large PRs from overwhelming the reviewer.',
        category: 'review',
        type: 'number',
        default: 50,
        editable: true,
        requiresRestart: false,
        validation: z.number().min(1).max(500),
        sensitive: false,
    },
    {
        key: 'review.maxDiffSize',
        label: 'Max Diff Size (characters)',
        description: 'PRs with a diff larger than this are skipped.',
        category: 'review',
        type: 'number',
        default: 100000,
        editable: true,
        requiresRestart: false,
        validation: z.number().min(1000).max(1000000),
        sensitive: false,
    },
    {
        key: 'review.prStateFilter',
        label: 'PR State Filter',
        description: 'Which PR states to review: open (active PRs only), closed (completed PRs only), or all.',
        category: 'review',
        type: 'enum',
        enumValues: ['open', 'closed', 'all'],
        default: 'open',
        editable: true,
        requiresRestart: false,
        validation: z.enum(['open', 'closed', 'all']),
        sensitive: false,
    },
    {
        key: 'claude.reviewTimeoutSeconds',
        label: 'Review Timeout',
        description: 'Maximum seconds to wait for Claude CLI to complete a review. Increase for large repositories.',
        category: 'claude',
        type: 'number',
        default: 300,
        editable: true,
        requiresRestart: false,
        validation: z.number().min(60).max(1800),
        sensitive: false,
    },
    // --- Non-editable settings ---
    {
        key: 'github.token',
        label: 'GitHub Token',
        description: 'Personal Access Token for GitHub API access.',
        category: 'providers',
        type: 'string',
        default: '',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: true,
    },
    {
        key: 'azureDevOps.token',
        label: 'Azure DevOps Token',
        description: 'Personal Access Token for Azure DevOps API access.',
        category: 'providers',
        type: 'string',
        default: '',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: true,
    },
    {
        key: 'azureDevOps.orgUrl',
        label: 'Azure DevOps Org URL',
        description: 'Azure DevOps organization URL (e.g. https://dev.azure.com/myorg).',
        category: 'providers',
        type: 'string',
        default: '',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: false,
    },
    {
        key: 'claude.cliPath',
        label: 'Claude CLI Path',
        description: 'Path to the claude binary.',
        category: 'claude',
        type: 'string',
        default: 'claude',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: false,
    },
    {
        key: 'claude.model',
        label: 'Claude Model',
        description: 'Specific model to use for reviews (leave empty for default).',
        category: 'claude',
        type: 'string',
        default: '',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: false,
    },
    {
        key: 'server.apiPort',
        label: 'API Port',
        description: 'Port for the Express API server.',
        category: 'server',
        type: 'number',
        default: 3001,
        editable: false,
        requiresRestart: true,
        validation: z.number(),
        sensitive: false,
    },
    {
        key: 'storage.dbPath',
        label: 'Database Path',
        description: 'Path to the SQLite database file.',
        category: 'storage',
        type: 'string',
        default: './data/reviews.db',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: false,
    },
    {
        key: 'storage.reposDir',
        label: 'Repos Directory',
        description: 'Directory for local git clones.',
        category: 'storage',
        type: 'string',
        default: './data/repos',
        editable: false,
        requiresRestart: true,
        validation: z.string(),
        sensitive: false,
    },
];
