/**
 * Generates a .coding-standards.md file for repositories that lack one.
 *
 * On first review of a repo, Claude CLI analyzes the codebase structure,
 * config files, and existing patterns to produce a coding standards document.
 * The result is stored in the database and written to the clone directory
 * before each review so Claude CLI can read it.
 */

import { execCommand } from '../utils/shell.js';
import { createModuleLogger } from '../shared/logger.js';

const logger = createModuleLogger('standards-generator');

export const STANDARDS_FILENAME = '.coding-standards.md';

const GENERATION_PROMPT = `
You are analyzing a codebase to generate a coding standards document. You MUST complete this in under 10 tool calls.

STEP 1 (1 call): Use Glob with pattern "*" at the repo root to see top-level files and directories.
STEP 2 (1-2 calls): Read package.json (or requirements.txt / go.mod / Cargo.toml) AND any CLAUDE.md or CONTRIBUTING.md if they exist at the root.
STEP 3 (1-2 calls): Read tsconfig.json or eslint config if present at the root. Use Glob with pattern "src/*" or the main source directory to see its structure.
STEP 4 (2-3 calls): Read 2-3 source files from DIFFERENT subdirectories to detect naming, imports, error handling, and architecture patterns.
STEP 5 (0 calls): Generate the document from what you learned. Do NOT make additional tool calls.

TOTAL: Maximum 10 tool calls. Stop exploring and generate the document once you have enough context.

Generate a markdown document with this structure:

# Coding Standards

> Auto-generated by AutoCodeReview. Edit this file from the UI to customize review rules.

## Tech Stack
## Project Structure
## Naming Conventions
## Import & Module Organization
## Error Handling
## Logging & Observability
## Validation
## Database & Data Access
## API Conventions
## Testing Standards
## Security Rules
## Architectural Boundaries
## Do NOT

Rules:
- Only document patterns that ACTUALLY EXIST. Do not invent conventions.
- Be specific with examples from the codebase.
- If a section has no discernible convention, write "No established convention detected".
- Keep it concise.

OUTPUT: Return ONLY the markdown content. No JSON wrapping, no preamble, no code fences around the entire output.
`.trim();

export class CodingStandardsGenerator {
    constructor(
        private readonly cliPath: string,
        private readonly timeoutSeconds: number,
        private model: string | undefined,
    ) {}

    /**
     * Updates the model used for subsequent standards generation. Called when
     * the `claude.model` setting changes at runtime. Pass `undefined` to let
     * the Claude CLI choose its own default.
     */
    setModel(model: string | undefined): void {
        this.model = model;
    }

    /**
     * Generates coding standards by spawning Claude CLI to analyze the codebase.
     * Returns the markdown content string.
     * Throws on failure.
     */
    async generate(repoPath: string): Promise<string> {
        logger.info('Generating coding standards', { repoPath });

        const args = [
            '--print',
            '--output-format', 'json',
            '--max-turns', '15',
            '--allowedTools', 'Read,Glob,Grep',
        ];

        if (this.model) {
            args.push('--model', this.model);
        }

        const result = await execCommand(this.cliPath, args, {
            cwd: repoPath,
            timeoutMs: this.timeoutSeconds * 1000,
            stdin: GENERATION_PROMPT,
        });

        if (result.exitCode !== 0) {
            logger.error('Standards generation failed', {
                repoPath,
                exitCode: result.exitCode,
                stderr: result.stderr.substring(0, 500),
            });
            throw new Error(
                `Standards generation failed (exit ${result.exitCode}): ${result.stderr.substring(0, 200)}`
            );
        }

        const content = this.extractContent(result.stdout);

        if (!content || content.length < 100) {
            logger.warn('Standards generation produced insufficient content', {
                repoPath,
                contentLength: content?.length ?? 0,
            });
            throw new Error('Standards generation produced insufficient content');
        }

        logger.info('Coding standards generated', {
            repoPath,
            contentLength: content.length,
            durationMs: result.durationMs,
        });

        return content;
    }

    /**
     * Extracts markdown content from Claude CLI output.
     * Handles both raw text and JSON envelope formats.
     */
    private extractContent(stdout: string): string {
        // Try JSON envelope first (--output-format json)
        try {
            const envelope = JSON.parse(stdout);
            if (typeof envelope.result === 'string') {
                return envelope.result.trim();
            }
            // Claude CLI JSON envelope may have content blocks
            if (Array.isArray(envelope.content)) {
                const textBlocks = envelope.content
                    .filter((block: { type?: string }) => block.type === 'text')
                    .map((block: { text?: string }) => block.text ?? '')
                    .join('\n');
                if (textBlocks) return textBlocks.trim();
            }
            if (Array.isArray(envelope)) {
                const textBlocks = envelope
                    .filter((msg: { type?: string }) => msg.type === 'text')
                    .map((msg: { text?: string }) => msg.text ?? '')
                    .join('\n');
                if (textBlocks) return textBlocks.trim();
            }
        } catch {
            // Not JSON — treat as raw text
        }

        return stdout.trim();
    }
}
