import type { ReviewDetail, Finding } from '../types';

function severityIcon(severity: string): string {
    switch (severity) {
        case 'critical': return '🔴';
        case 'warning': return '🟡';
        case 'info': return '🔵';
        case 'praise': return '🟢';
        case 'clean': return '✅';
        default: return '⚪';
    }
}

function renderFinding(f: Finding, index: number): string {
    const loc = f.line_start
        ? (f.line_end && f.line_end !== f.line_start ? `${f.file}:${f.line_start}-${f.line_end}` : `${f.file}:${f.line_start}`)
        : f.file;

    const parts: string[] = [
        `### ${index}. ${severityIcon(f.severity)} ${f.title}`,
        '',
        `- **Type:** ${f.type}`,
        `- **Severity:** ${f.severity}`,
        `- **Location:** \`${loc}\``,
        '',
        f.description,
    ];

    if (f.code_snippet) {
        parts.push('', '**Code:**', '```' + (f.language ?? ''), f.code_snippet, '```');
    }

    if (f.suggestion) {
        parts.push('', '**Suggestion:**', '', f.suggestion);
    }

    return parts.join('\n');
}

export function buildReviewMarkdown(review: ReviewDetail): string {
    const lines: string[] = [
        `# Code Review: PR #${review.pr_number}`,
        '',
        `**${review.pr_title}**`,
        '',
        '## Details',
        '',
        `- **Repository:** ${review.repo_full_name}`,
        `- **Author:** ${review.pr_author}`,
        `- **Branch:** \`${review.branch_name}\``,
        `- **Commit:** \`${review.commit_sha}\``,
        `- **Overall severity:** ${severityIcon(review.severity)} ${review.severity}`,
        `- **Status:** ${review.status}`,
        `- **Files changed:** ${review.stats.files_changed} (+${review.stats.additions} -${review.stats.deletions})`,
        `- **Reviewed at:** ${new Date(review.created_at).toLocaleString()}`,
    ];

    if (review.claude_model) {
        lines.push(`- **Model:** ${review.claude_model}`);
    }
    if (review.pr_url) {
        lines.push(`- **PR URL:** ${review.pr_url}`);
    }

    if (review.commit_message) {
        lines.push('', '## Commit message', '', `> ${review.commit_message}`);
    }

    if (review.summary) {
        lines.push('', '## Summary', '', review.summary);
    }

    lines.push('', `## Findings (${review.findings.length})`);

    if (review.findings.length === 0) {
        lines.push('', '_No findings._');
    } else {
        review.findings.forEach((f, i) => {
            lines.push('', renderFinding(f, i + 1));
        });
    }

    if (review.files_reviewed && review.files_reviewed.length > 0) {
        lines.push('', '## Files reviewed', '', ...review.files_reviewed.map(f => `- \`${f}\``));
    }

    lines.push('', '---', `_Generated by AutoCodeReview_`);

    return lines.join('\n');
}

export function downloadReviewReport(review: ReviewDetail): void {
    const markdown = buildReviewMarkdown(review);
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const repoSlug = review.repo_full_name.replace(/[\\/]/g, '_');
    const filename = `review_${repoSlug}_PR${review.pr_number}_${review.commit_sha.slice(0, 7)}.md`;

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
